### ISSUE TITLE
run problem

### ISSUE THREAD

**Issue by goog** [ysymyth/tree-of-thought-llm#18]
```bash
cheng in 🌐 cheng-virtual-machine in tree-of-thought-llm on  master via 🐍 v3.10.6
❯ python3 run.py --task game24 --task_file_path 24.csv  --backend gpt-3.5-turbo
Namespace(backend='gpt-3.5-turbo', temperature=0.7, task='game24', task_file_path='24.csv', task_start_index=900, task_end_index=1000, naive_run=False, prompt_sample=None, method_generate=None, method_evaluate=None, method_select=None, n_generate_sample=1, n_evaluate_sample=1, n_select_sample=1)
functools.partial(<function gpt at 0x7f504160cf70>, model='gpt-3.5-turbo', temperature=0.7)
Traceback (most recent call last):
  File "/home/cheng/tree-of-thought-llm/run.py", line 160, in <module>
    run(args)
  File "/home/cheng/tree-of-thought-llm/run.py", line 113, in run
    ys, info = solve(args, task, i)
  File "/home/cheng/tree-of-thought-llm/run.py", line 64, in solve
    new_ys = list(itertools.chain(*new_ys))
UnboundLocalError: local variable 'new_ys' referenced before assignment

```
on ubuntu22.04

**Comment by goog** [comment]
hello! how to run the code?  i dont know what does task_file_path do?

**Comment by goog** [comment]
change OPENAI_API_BASE.

**Comment by arturohernandez10** [comment]
The function checks if args.method_generate is either 'sample' or 'propose', but in your case, args.method_generate is None
